# Generated by Django 5.1 on 2024-08-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
