# Generated by Django 5.1 on 2024-08-16 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_showtimes_date_alter_showtimes_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
